spring:
  mongodb:
    username: dima
    password: dima
    host: localhost
    port: 27017
    database: customer
    authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: OrderConformation:io.github.platovd.ecommerce.kafka.OrderConfirmation,PaymentConformation:io.github.platovd.ecommerce.notification.PaymentNotificationRequest
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: dima
    password: dima
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writhtimeout: 5000
server:
  port: 8040